### ISSUE TITLE
Randomly spawned snakes should always spawn on same color squares.

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/rules#12]
**What's the problem?**
Currently non-standard board sizes will place the snakes in random starting positions - if two snakes are spawned within one move of eachother, this means head-to-head collisions are impossible between those two snakes. The old engine addressed this by always spawning random snakes on all "white" or all "black" squares, assuming the board was checker patterns (like a chess board).

**What's the solution?**
Re-implement same color spawning when spawning snakes randomly.
See https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go#L101

**Other Notes**
Test cases should be added that enforce this with a large number of random spawns.

**Comment by sjbcastro** [comment]
Hi, I was thinking of taking this one on. Are there any guidelines/coding conventions I need to be aware of before putting in a pull request? It's my first time contributing to an open source project and first time using Go, but I think this one should be straightforward enough :)

**Comment by sjbcastro** [comment]
@bvanvugt the changes didn't take very long so I have just gone ahead and created a pull request: https://github.com/BattlesnakeOfficial/rules/pull/14

Tried to link this issue to the pull request, not sure if I need write access to the repo to do that.
