### ISSUE TITLE
Overlapping a teammate in Squad game allows overlapping of own body when on the same coords

### ISSUE THREAD

**Issue by tyrelh** [BattlesnakeOfficial/rules#16]
Example game: [https://play.battlesnake.com/g/92dac2fc-2395-41fb-86f7-20d6ecdf31d9/](https://play.battlesnake.com/g/92dac2fc-2395-41fb-86f7-20d6ecdf31d9/)

In this Squad game, the ruleset did not cause *Zero Cool* to die on turn 51. *Zero Cool* returned `"left"`, this caused it to overlap its teammate *Crash Override* but also its own body which *Crash Override* was already overlapping.

![](https://battlesnake-logs.s3-us-west-2.amazonaws.com/Screen+Shot+2020-06-09+at+2.44.27+PM.png)

Turn 51 JSON:
```json
{"game":{"id":"92dac2fc-2395-41fb-86f7-20d6ecdf31d9","timeout":500},"turn":51,"board":{"height":11,"width":11,"food":[{"x":8,"y":9}],"snakes":[{"id":"gs_6vHrXdTDSFvtgQhyQPYyW4WM","name":"teamBoi","health":92,"body":[{"x":1,"y":4},{"x":1,"y":3},{"x":0,"y":3},{"x":0,"y":2},{"x":1,"y":2},{"x":2,"y":2}],"head":{"x":1,"y":4},"length":6,"shout":"","team":"BirdSnakers"},{"id":"gs_qdkfVmctDcBX7K8yqx6DmPJ6","name":"Node-Red-Bellied-Black-Snake","health":92,"body":[{"x":1,"y":8},{"x":2,"y":8},{"x":2,"y":9},{"x":3,"y":9},{"x":4,"y":9},{"x":4,"y":10}],"head":{"x":1,"y":8},"length":6,"shout":"","team":"BirdSnakers"},{"id":"gs_rqV4HyyhPDcgrtwWpSrSXjd9","name":"Crash Override","health":93,"body":[{"x":2,"y":7},{"x":2,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":4,"y":5},{"x":5,"y":5},{"x":6,"y":5}],"head":{"x":2,"y":7},"length":7,"shout":"","team":"Hackers"},{"id":"gs_KFdRPHptr6bxpQBcyQhCP7KQ","name":"Zero Cool","health":93,"body":[{"x":6,"y":5},{"x":5,"y":5},{"x":5,"y":4},{"x":5,"y":3},{"x":4,"y":3},{"x":3,"y":3},{"x":3,"y":4}],"head":{"x":6,"y":5},"length":7,"shout":"","team":"Hackers"}]},"you":{"id":"gs_KFdRPHptr6bxpQBcyQhCP7KQ","name":"Zero Cool","health":93,"body":[{"x":6,"y":5},{"x":5,"y":5},{"x":5,"y":4},{"x":5,"y":3},{"x":4,"y":3},{"x":3,"y":3},{"x":3,"y":4}],"head":{"x":6,"y":5},"length":7,"shout":"","team":"Hackers"}}
```

On turn 52, there are 3 snake segments on `{x: 5, y: 5}` (v1 coords). *Zero Cool* has 2 body segments on that space as well as *Crash Overrides* tail.

Turn 52 JSON:
```json
{"game":{"id":"92dac2fc-2395-41fb-86f7-20d6ecdf31d9","timeout":500},"turn":52,"board":{"height":11,"width":11,"food":[{"x":8,"y":9}],"snakes":[{"id":"gs_6vHrXdTDSFvtgQhyQPYyW4WM","name":"teamBoi","health":91,"body":[{"x":1,"y":5},{"x":1,"y":4},{"x":1,"y":3},{"x":0,"y":3},{"x":0,"y":2},{"x":1,"y":2}],"head":{"x":1,"y":5},"length":6,"shout":"","team":"BirdSnakers"},{"id":"gs_qdkfVmctDcBX7K8yqx6DmPJ6","name":"Node-Red-Bellied-Black-Snake","health":91,"body":[{"x":0,"y":8},{"x":1,"y":8},{"x":2,"y":8},{"x":2,"y":9},{"x":3,"y":9},{"x":4,"y":9}],"head":{"x":0,"y":8},"length":6,"shout":"","team":"BirdSnakers"},{"id":"gs_rqV4HyyhPDcgrtwWpSrSXjd9","name":"Crash Override","health":92,"body":[{"x":1,"y":7},{"x":2,"y":7},{"x":2,"y":6},{"x":3,"y":6},{"x":4,"y":6},{"x":4,"y":5},{"x":5,"y":5}],"head":{"x":1,"y":7},"length":7,"shout":"","team":"Hackers"},{"id":"gs_KFdRPHptr6bxpQBcyQhCP7KQ","name":"Zero Cool","health":92,"body":[{"x":5,"y":5},{"x":6,"y":5},{"x":5,"y":5},{"x":5,"y":4},{"x":5,"y":3},{"x":4,"y":3},{"x":3,"y":3}],"head":{"x":5,"y":5},"length":7,"shout":"","team":"Hackers"}]},"you":{"id":"gs_KFdRPHptr6bxpQBcyQhCP7KQ","name":"Zero Cool","health":92,"body":[{"x":5,"y":5},{"x":6,"y":5},{"x":5,"y":5},{"x":5,"y":4},{"x":5,"y":3},{"x":4,"y":3},{"x":3,"y":3}],"head":{"x":5,"y":5},"length":7,"shout":"","team":"Hackers"}}
```

The game continues for several more turns with *Zero Cool* having body segments overlapping. This also causes an artifact on the arena frontend, but that is just a symptom of this ruleset bug.

**Expected behaviour:** Hitting your own body should cause a death, even if your teammate is overlapping your body on those coords. On turn 51 of the example game *Zero Cool* should have died by **collision with own body**

**Comment by bvanvugt** [comment]
@sjbcastro hoping you might want to take a look at this :)

The offending code will be in this function:
https://github.com/BattlesnakeOfficial/rules/blob/master/team.go#L50

Should be easy to write a unit test for too - let me know if you'll have a chance.

**Comment by bvanvugt** [comment]
An alternative approach could be guaranteeing that self-collisions take priority over other collisions, here:
https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go#L262

**Comment by bvanvugt** [comment]
I ended up taking the prioritization approach to solving this, by prioritizing self-collisions over non-self-collisions. Added unit tests to catch any regressions.
