### ISSUE TITLE
Elimination state is not initialized from prevState

### ISSUE THREAD

**Issue by glennhartmann** [BattlesnakeOfficial/rules#19]
Many of the functions in standard.go (moveSnakes, reduceSnakeHealth, maybeFeedSnakes) rely on EliminatedCause to prevent eliminated snakes from moving, starving, and consuming food.

However, EliminatedCause is not initialized from prevState at the beginning of the function (https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go#L203), so eliminated snakes will not register as being eliminated until maybeEliminateSnakes is called, which is the very last thing that happens in the function.

**Comment by xtagon** [comment]
Possibly related to this recent change? https://github.com/BattlesnakeOfficial/rules/commit/a342f87ed6c18f16d3d0fc099d94d047e31d4611

**Comment by bvanvugt** [comment]
Ah, you're right - we don't copy Eliminated state from prevState, but we could/should.

Note that the production game is not impacted by this because eliminated snakes are removed from subsequent calls.

@glennhartmann I'm curious - you must be running the rules code locally to find this?

**Comment by bvanvugt** [comment]
Note that a fix here should include a unit test that specifically covers this (possibly by using an initial state of only eliminated snakes?)

**Comment by glennhartmann** [comment]
@bvanvugt yeah - it's a convenient way to generate potential board states after a given move to help a snake can evaluate the utility of certain actions.

I was also thinking of writing an engine around this code - having my snake battle itself (or other open-source snakes) locally would improve iteration time for small tweaks without having to deploy new code to cloud servers every time.

**Comment by xtagon** [comment]
> I was also thinking of writing an engine around this code - having my snake battle itself (or other open-source snakes) locally would improve iteration time for small tweaks without having to deploy new code to cloud servers every time.

I'm trying something like that as well, so if we could reproduce this with a test case it would be easy for anyone to transfer over to alternative rules implementations as well as fixing in the official engine

**Comment by bvanvugt** [comment]
Gotcha - makes sense. We'd *really* like to include a simple, synchronous engine in this code itself. Just a simple CLI tool that takes a URL and some config.

Lots of talk the past few weeks about this in the slack group too. I'll see if I can write an issue for it this week, maybe someone can offer to help out.

**Comment by xtagon** [comment]
Well, there's really two separate use cases, they're different. People want an engine to use for testing in development, but what @glennhartmann and I are saying is that we would like to plug in the official rulesets into our snake's decision making code. For example, I perform a game tree search which simulates turns in future positions, then evaluates them. An engine wouldn't solve that. Since my snake is not written in Go, I had to re-implement the official rules (which is fine, but it's not easy to test yet). Maybe it would be useful to have this repo implement a CLI program that takes stdin input, creates the next board state (simulates the turn), and returns the result to stdout. Then any snake in any language could use the official rules.

**Comment by bvanvugt** [comment]
@xtagon ahhh gotcha. yes, I think a CLI/binary engine command is a neat solution to that. I'll make sure what we do here supports that. Would you be okay with just JSON output?

**Comment by xtagon** [comment]
Thanks! Yeah JSON output would be great 👍

**Comment by bvanvugt** [comment]
@glennhartmann Give the latest release a spin and let me know what you think. Should be working now.

**Comment by glennhartmann** [comment]
(sorry, I've been ignoring github for a while...)

Looks great now, thanks!
