### ISSUE TITLE
Add a command line tool to run games locally

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/rules#20]
## Problem
Previous versions of the game engine allowed games to be run locally using a [builtin CLI](https://github.com/battlesnakeio/engine#running-a-game-with-the-cli). This behaviour was removed when we separated the game logic into its own go module (this code). The community has been asking for similar functionality to help develop and iterate on Battlesnakes faster, and we'd like to provide it.

## Proposal
Create a command line tool that:
- loads config from a JSON file
- runs a game synchronously
- outputs the final results to an output JSON file (or stdout)

## Notes
- We'd like to use [cobra](https://github.com/spf13/cobra) to build this

**Comment by bvanvugt** [comment]
New CLI has been added with PR #25!

**Comment by glennhartmann** [comment]
> New CLI has been added with PR #25!

This is awesome! Thanks!
