### ISSUE TITLE
Support Query Parameters in Snake URL

### ISSUE THREAD

**Issue by SamWheating** [BattlesnakeOfficial/rules#21]
My Snake uses a heuristic function which depends a few key constants (lets call them `depth` and `count`). Modifying the value of these constants has a large impact on the snake's performance and it is difficult to "tune" it to the right values. 

If I could provide a snake URL with the constants provided as query parameters like `https://mysnake.com?depth=10&count=100` it would allow me to upload different variants of my snake running from the same server/endpoint, or quickly tweak values without having to re-deploy my server. 

This could allow for additional logic as well, like having multiple snake algorithms running on one server and selecting the algorithm to used based on a query param. 

This doesn't seem to be supported now, is there a chance it could be in the future? Let me know what you think.

**Comment by bvanvugt** [comment]
@SamWheating Thanks for the suggestion! We just updated the game engine to support this - let me know here (or on slack) if you run into trouble :)
