### ISSUE TITLE
New constants for StandardRuleset errors

### ISSUE THREAD

**Issue by bvanvugt** [BattlesnakeOfficial/rules#5]
**What is the problem?**
Error messages are hardcoded strings throughout standard.go and standard_test.go

**What is the solution?**
Define new constants for possible errors, possibly in standard.go.

**Comment by md-hexdrive** [comment]
I could take a crack at this.

P.S. Battlesnake is awesome! Thanks for making it!

**Comment by bvanvugt** [comment]
@md-hexdrive Hi! Sorry for the delay here.

Sounds great, let me know if I can point you in a direction to get going. The goal is to populate this:
https://github.com/BattlesnakeOfficial/rules/blob/master/standard.go#L29

**Comment by md-hexdrive** [comment]
@bvanvugt Okay Thanks!

I submitted a pull-request yesterday to fix this:
https://github.com/BattlesnakeOfficial/rules/pull/24

I'd love to help you guys out in the future!
